// <auto-generated />
using System;
using BoxTrack.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoxTrack.Infrastructure.Migrations
{
    [DbContext(typeof(BoxTrackDbContext))]
    [Migration("20261008115745_AddTscLabelTemplates")]
    partial class AddTscLabelTemplates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoxTrack.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text")
                        .HasColumnName("after_json");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text")
                        .HasColumnName("before_json");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.BarcodeLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BarcodeValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barcode_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<long?>("DispatchRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("dispatch_record_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int>("ItemCode")
                        .HasColumnType("integer")
                        .HasColumnName("item_code");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int?>("LabelLogoId")
                        .HasColumnType("integer")
                        .HasColumnName("label_logo_id");

                    b.Property<string>("LogoMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_mode");

                    b.Property<DateOnly>("ManufactureDate")
                        .HasColumnType("date")
                        .HasColumnName("manufacture_date");

                    b.Property<string>("ProductionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PendingProduction")
                        .HasColumnName("production_status");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<int>("SerialNumber")
                        .HasColumnType("integer")
                        .HasColumnName("serial_number");

                    b.Property<long?>("StockReceiptId")
                        .HasColumnType("bigint")
                        .HasColumnName("stock_receipt_id");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeValue")
                        .IsUnique();

                    b.HasIndex("DispatchRecordId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LabelLogoId");

                    b.HasIndex("ProductionStatus");

                    b.HasIndex("StockReceiptId");

                    b.ToTable("barcode_label", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("text")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("text")
                        .HasColumnName("address2");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("LegacyId")
                        .HasColumnType("integer")
                        .HasColumnName("legacy_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Pincode")
                        .HasColumnType("text")
                        .HasColumnName("pincode");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("department", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.DispatchRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DispatchDate")
                        .HasColumnType("date")
                        .HasColumnName("dispatch_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<int>("LabelCount")
                        .HasColumnType("integer")
                        .HasColumnName("label_count");

                    b.Property<string>("SalesOrderNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sales_order_number");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_file_name");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceNumber");

                    b.HasIndex("SalesOrderNumber");

                    b.ToTable("dispatch_record", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("integer")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal>("GrossWeightKg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("gross_weight_kg");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("PackagingPerBox")
                        .HasColumnType("integer")
                        .HasColumnName("packaging_per_box");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.LabelLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relative_path");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("label_logo", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.LabelTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<double>("GapMm")
                        .HasColumnType("double precision")
                        .HasColumnName("gap_mm");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision")
                        .HasColumnName("height_mm");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Orientation")
                        .HasColumnType("integer")
                        .HasColumnName("orientation");

                    b.Property<int>("PrinterType")
                        .HasColumnType("integer")
                        .HasColumnName("printer_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<double>("WidthMm")
                        .HasColumnType("double precision")
                        .HasColumnName("width_mm");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("label_template", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.LabelTemplateElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BarcodeType")
                        .HasColumnType("text")
                        .HasColumnName("barcode_type");

                    b.Property<int>("BorderThicknessDots")
                        .HasColumnType("integer")
                        .HasColumnName("border_thickness_dots");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("ElementType")
                        .HasColumnType("integer")
                        .HasColumnName("element_type");

                    b.Property<int>("FitMode")
                        .HasColumnType("integer")
                        .HasColumnName("fit_mode");

                    b.Property<string>("FontName")
                        .HasColumnType("text")
                        .HasColumnName("font_name");

                    b.Property<int>("FontSize")
                        .HasColumnType("integer")
                        .HasColumnName("font_size");

                    b.Property<double>("HeightMm")
                        .HasColumnType("double precision")
                        .HasColumnName("height_mm");

                    b.Property<bool>("HumanReadable")
                        .HasColumnType("boolean")
                        .HasColumnName("human_readable");

                    b.Property<int?>("LogoId")
                        .HasColumnType("integer")
                        .HasColumnName("logo_id");

                    b.Property<int>("Rotation")
                        .HasColumnType("integer")
                        .HasColumnName("rotation");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("template_id");

                    b.Property<double>("WidthMm")
                        .HasColumnType("double precision")
                        .HasColumnName("width_mm");

                    b.Property<double>("Xmm")
                        .HasColumnType("double precision")
                        .HasColumnName("xmm");

                    b.Property<double>("Ymm")
                        .HasColumnType("double precision")
                        .HasColumnName("ymm");

                    b.Property<int>("ZIndex")
                        .HasColumnType("integer")
                        .HasColumnName("z_index");

                    b.HasKey("Id");

                    b.HasIndex("LogoId");

                    b.HasIndex("TemplateId");

                    b.ToTable("label_template_element", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.PrintJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("Copies")
                        .HasColumnType("integer")
                        .HasColumnName("copies");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_name");

                    b.Property<string>("DocumentReference")
                        .HasColumnType("text")
                        .HasColumnName("document_reference");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("printer_name");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text")
                        .HasColumnName("requested_by");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("print_job", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.PrinterConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActiveTemplateId")
                        .HasColumnType("integer")
                        .HasColumnName("active_template_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("Dpi")
                        .HasColumnType("integer")
                        .HasColumnName("dpi");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("printer_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTemplateId");

                    b.HasIndex("Category");

                    b.ToTable("printer_configuration", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.StockReceipt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("batch_number");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FromBarcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_barcode");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("ToBarcode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_barcode");

                    b.HasKey("Id");

                    b.HasIndex("BatchNumber");

                    b.HasIndex("ItemId");

                    b.ToTable("stock_receipt", (string)null);
                });

            modelBuilder.Entity("BoxTrack.Domain.BarcodeLabel", b =>
                {
                    b.HasOne("BoxTrack.Domain.DispatchRecord", "DispatchRecord")
                        .WithMany("BarcodeLabels")
                        .HasForeignKey("DispatchRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BoxTrack.Domain.Item", "Item")
                        .WithMany("BarcodeLabels")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BoxTrack.Domain.LabelLogo", "LabelLogo")
                        .WithMany("BarcodeLabels")
                        .HasForeignKey("LabelLogoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BoxTrack.Domain.StockReceipt", "StockReceipt")
                        .WithMany("BarcodeLabels")
                        .HasForeignKey("StockReceiptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DispatchRecord");

                    b.Navigation("Item");

                    b.Navigation("LabelLogo");

                    b.Navigation("StockReceipt");
                });

            modelBuilder.Entity("BoxTrack.Domain.DispatchRecord", b =>
                {
                    b.HasOne("BoxTrack.Domain.Customer", "Customer")
                        .WithMany("Dispatches")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BoxTrack.Domain.Item", b =>
                {
                    b.HasOne("BoxTrack.Domain.Department", "Department")
                        .WithMany("Items")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BoxTrack.Domain.LabelTemplateElement", b =>
                {
                    b.HasOne("BoxTrack.Domain.LabelLogo", "Logo")
                        .WithMany()
                        .HasForeignKey("LogoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BoxTrack.Domain.LabelTemplate", "Template")
                        .WithMany("Elements")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logo");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("BoxTrack.Domain.PrinterConfiguration", b =>
                {
                    b.HasOne("BoxTrack.Domain.LabelTemplate", "ActiveTemplate")
                        .WithMany()
                        .HasForeignKey("ActiveTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveTemplate");
                });

            modelBuilder.Entity("BoxTrack.Domain.StockReceipt", b =>
                {
                    b.HasOne("BoxTrack.Domain.Item", "Item")
                        .WithMany("StockReceipts")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("BoxTrack.Domain.Customer", b =>
                {
                    b.Navigation("Dispatches");
                });

            modelBuilder.Entity("BoxTrack.Domain.Department", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BoxTrack.Domain.DispatchRecord", b =>
                {
                    b.Navigation("BarcodeLabels");
                });

            modelBuilder.Entity("BoxTrack.Domain.Item", b =>
                {
                    b.Navigation("BarcodeLabels");

                    b.Navigation("StockReceipts");
                });

            modelBuilder.Entity("BoxTrack.Domain.LabelLogo", b =>
                {
                    b.Navigation("BarcodeLabels");
                });

            modelBuilder.Entity("BoxTrack.Domain.LabelTemplate", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("BoxTrack.Domain.StockReceipt", b =>
                {
                    b.Navigation("BarcodeLabels");
                });
#pragma warning restore 612, 618
        }
    }
}
